language: java
branches:
  only:
  - develop
  - /^release-[0-999].[0-999]$/
  - master
notifications:
  email:
    recipients:
    - j.bernal@upm.es
script:
#Test unitario y de integracion en perfil DEV, con cobertura
- mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=miw-upm-github -Dsonar.login=$SONAR
#Deploy https://betca-tpv-spring.herokuapp.com/api/v0/api-info
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master
